name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      shell: pwsh
      run: |
        .\Backup-Policies.ps1
