# File: .github/workflows/workflow.yml

on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/setup-python@v3
      - run: |
          pip install --pre azure-containerregistry
          pip install --pre azure-identity
          pwd
          ls **/**
          python .github/del_old_containers.py