# File: .github/workflows/workflow.yml

on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.

      - uses: actions/setup-python@v3
      - run: |
          pip install --pre azure-containerregistry
          pip install --pre azure-identity

      - name: Execute Python script # Run the run.py to get the latest data
        run: python del_old_containers.py
